apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every-mins
spec:
  schedule: "*/1 * * * *" # mins hours date month week
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: main
              image: luksa/batch-job
