apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia # rc
spec:
  replicas: 5
  selector:
    app: kubia # 和下面的template.metadata.labels.app=kubia 必须一样
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia # pod container image
          ports:
            - containerPort: 8080 # container port
